##
# Copyright (c) 2010-2016 Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

all:

  title: Eureka Framework
  titles:
    full:
      part1: Eureka
      part2: Framework
    short:
      part1: Eka
      part2: F

  charset: utf-8
  description: Eureka Framework
  keywords: eureka, framework, php
  author: Romain Cottard
  version: 0.9.0
  copyright: 2015 - Romain Cottard

dev:
  title: Eureka Framework - DEV

preprod:
  title: Eureka Framework - PREPROD

prod:
  title: Eureka Framework - PROD