##
# Copyright (c) 2010-2016 Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# File to configure theming

dev:

preprod:

prod:

all:
  php:
    theme: AdminLTE
    layout: EKA_PACKAGE/Example/Module/Layout

  static:
    main:
      path: /static/main
      css: [ main.css ]
      js:  [ html5shiv.min.js, respond.min.js ]

    theme:
      path: /static/themes/admin-lte
      css:  [ admin-lte.min.css, /skins/skin-black.min.css ]
      js:   [ app.min.js ]